### PR TITLE
Fixing artemis configuration

### PR DESCRIPTION
**Pull request by franz1981**
I've fixed the artemis configuration to just use a single broker configuration and to configure via JHM param the delivery type of producers in order to correctly deal with the required durability semantic.

The journal used is MAPPED with no datasync to match the default (single node) kafka behaviour ie process-failure durability guarantees (and not power-failure durability guarantees).

A note on the semantic: JMS queues in artemis are single-threaded beasts (from the consumer point of view) hence their performance is limited by the CPU speed of the machine using it.
A more fair scalability benchmark would be to use topics or different (named) queues with their set of producers/consumers: anything different *cannot* scale (and I believe the same is for classic activemq)

I cannot find where the JVM parameters used to run the broker are set: artemis (differently from kafka or others) requires a generous amount of heap memory to save messages from being paged in-out in case of producers outpacing consumers, hence it's key to increase the heap memory enough to save paging to happen for non-persistent messages.

### CODE REVIEW

**Comment by franz1981** [comment]
One question: why just not persistent param?

**Comment by danielrigos** [comment]
Hey @franz1981,

Thank you for proposing these changes.

> I've fixed the artemis configuration to just use a single broker configuration and to configure via JHM param the delivery type of producers in order to correctly deal with the required durability semantic.

We also think having just one config file is fine, as persistence of messages can be determined in code, it doesn't _need_ to be determined in the config file. Adjustments have been made to switch to one config file.

>The journal used is MAPPED with no datasync to match the default (single node) kafka behaviour ie process-failure durability guarantees (and not power-failure durability guarantees).

We agree that switching the journal type to better match our other testing environments (Kafka, MQ, Rabbit, etc.) is a good decision. The config file will use your new journal settings.

>A more fair scalability benchmark would be to use topics or different (named) queues with their set of producers/consumers: anything different cannot scale (and I believe the same is for classic activemq)

Apologies if I misunderstood this, but I believe this means that the producer would perform better producing to a multitude of queues (as opposed to one, which becomes very large towards the end of the test), which makes sense, but doesn't fall in line with our testing environment. For example, IBM MQ saw little to no impact on throughput despite a massive queue depth. This is an important distinction when you consider enterprise/production environments that have millions of messages being transferred. You are correct that Artemis scales in a different way, and producing to multiple queues could be another benchmark all together (where Artemis shines), but in our case, we wanted to test the difference (in producer throughput) found between using a single queue across all middleware services. 

As for consuming, the consumers for all MQ systems in our test read from 5 queues (difference being message size in bytes for each queue.) 

>I cannot find where the JVM parameters used to run the broker are set: artemis (differently from kafka or others) requires a generous amount of heap memory to save messages from being paged in-out in case of producers outpacing consumers, hence it's key to increase the heap memory enough to save paging to happen for non-persistent messages.

To strictly change the JVM options (heap size, not Artemis properties like paging/journal), you can edit a `artemis.profile.cmd` found in your broker's /etc/ folder (i.e. `c:/artemis/bin/<yourBroker>/etc/`). Around line 36, you can see `JAVA_ARGS` being set, edit the -Xms and -Xmx values to adjust your JVM Heap size. How much to allow of course will depend on your system, but you can double the default values (-Xms1024M , -Xmx2048m) and go from there to see what works best. 

> One question: why just not persistent param?

The way our CyBench metadata works, it wouldn't be feasible to accurately categorize the results of each method/test on our web application (https://app.cybench.io/cybench/). By mixing persistent and non-persistent messages in the same test, scores/comparisons wouldn't be accurately reflected on the web app.

**Comment by franz1981** [comment]
@danielrigos where the results are published? which hw/OS is using?
configuration both client/server side depends by it and I would like to fix things in order to be fair with the used platform :)

**Comment by spencerspitz** [comment]
@franz1981 A public report is published here https://www.nastel.com/performance-benchmarking/. It details the environment (hw/OS) along with procedure, benchmark scores, etc.

**Comment by franz1981** [comment]
thanks @spencerspitz 
I'm a bit concerned about the reliability of such numbers, because they are using Windows for platforms that are optimized and designed to run at their best with linux (both kafka and artemis are built around this assumption, the former because it leverage zero copy transfer and OS page cache, the latter because MAPPED and ASYNCIO journal assume a linux platform to work to its best)

The other thing is related JMH itself that should be run on dedicated cores, no noisy neighbours, the right nano time granularity (windows 7 won't provide it) and turbo boost disabled, if possible.

**Comment by spencerspitz** [comment]
@franz1981 
We understand that each product may not be optimized for our specific environment but wanted a comparison of how they performed against each other within that environment. A different benchmark could be comparing them each in their respective preferred environments. There are different ways to compare these types of applications and we wanted to remain consistent in hw/OS variables for our measurements.

**Pull request merged**
